name: Lint source code
on: push

jobs:
  run:
    name: Lint with ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: echo Install dependencies!

      - name: Send message to ms teams
        uses: dhollerbach/github-action-send-message-to-ms-teams@1.0.10
        with:
          webhook: 'https://outlook.office.com/webhook/d25675f1-57eb-44b5-8ff9-bbe9a23c80b5@7d847b00-9cb2-4e8b-9f14-fb58de4bcdde/IncomingWebhook/4964e3d3a0ea481293debb3bd989e21f/e5538fbf-2964-4b65-b959-2142b0fe16d5'
          message: '{
    "type": "message",
    "attachments": [
        {
            "contentType": "application/vnd.microsoft.card.adaptive",
            "contentUrl": null,
            "content": {
                "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
                "type": "AdaptiveCard",
                "version": "1.2",
                "body": [
                    {
                        "type": "TextBlock",
                        "text": "Publish Adaptive Card Schema",
                        "weight": "bolder",
                        "size": "medium"
                    },
                    {
                        "type": "ColumnSet",
                        "columns": [
                            {
                                "type": "Column",
                                "width": "auto",
                                "items": [
                                    {
                                        "type": "Image",
                                        "url": "https://pbs.twimg.com/profile_images/3647943215/d7f12830b3c17a5a9e4afcc370e3a37e_400x400.jpeg",
                                        "size": "small",
                                        "style": "person"
                                    }
                                ]
                            },
                            {
                                "type": "Column",
                                "width": "stretch",
                                "items": [
                                    {
                                        "type": "TextBlock",
                                        "text": "Matt Hidinger",
                                        "weight": "bolder",
                                        "wrap": true
                                    },
                                    {
                                        "type": "TextBlock",
                                        "spacing": "none",
                                        "text": "Created {{DATE(2017-02-14T06:08:39Z, SHORT)}}",
                                        "isSubtle": true,
                                        "wrap": true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "type": "TextBlock",
                        "text": "Now that we have defined the main rules and features of the format, we need to produce a schema and publish it to GitHub. The schema will be the starting point of our reference documentation.",
                        "wrap": true
                    },
                    {
                        "type": "FactSet",
                        "facts": [
                            {
                                "title": "Board:",
                                "value": "Adaptive Cards"
                            },
                            {
                                "title": "List:",
                                "value": "Backlog"
                            },
                            {
                                "title": "Assigned to:",
                                "value": "Matt Hidinger"
                            },
                            {
                                "title": "Due date:",
                                "value": "Not set"
                            }
                        ]
                    }
                ],
                "actions": [
                    {
                        "type": "Action.ShowCard",
                        "title": "Set due date",
                        "card": {
                            "type": "AdaptiveCard",
                            "body": [
                                {
                                    "type": "Input.Date",
                                    "id": "dueDate"
                                },
                                {
                                    "type": "Input.Text",
                                    "id": "comment",
                                    "placeholder": "Add a comment",
                                    "isMultiline": true
                                }
                            ],
                            "actions": [
                                {
                                    "type": "Action.Submit",
                                    "title": "OK"
                                }
                            ],
                            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
                        }
                    },
                    {
                        "type": "Action.OpenUrl",
                        "title": "View",
                        "url": "https://adaptivecards.io"
                    }
                ]
            }
        }
    ]
}'
          
      - name: Send message to ms teams
        run: echo Update source code!


